import React, { useEffect, useState } from 'react';
import { createAgencySubmission, getAgencyWorkspace, reviseAgencySubmission, updateAgencyProfile } from '../services/api.js';

const TYPES = [['BID', 'Tender bid'], ['PROGRESS_UPDATE', 'Progress update'], ['GEO_EVIDENCE', 'Geo-tagged evidence'], ['INVOICE', 'Invoice / funding claim'], ['COMPLETION_CERTIFICATE', 'Completion certificate'], ['CLARIFICATION', 'Clarification response'], ['REMEDIATION_PLAN', 'Risk remediation plan']];
const money = (value) => `Rs ${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 1 })} L`;

export default function AgencyWorkspace() {
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [tab, setTab] = useState('overview');
  const [form, setForm] = useState({ type: 'PROGRESS_UPDATE', workId: '', title: '', details: '', progress: '', invoiceAmount: '', proposedAmount: '', proposedDurationDays: '', latitude: '', longitude: '', attachmentName: '', attachmentUrl: '' });
  const [saving, setSaving] = useState(false);
  const [compliance, setCompliance] = useState({ registrationNumber: '', qualifications: '', sectorCoverage: '', geographicCoverage: '', documentName: '', documentUrl: '' });
  const load = () => getAgencyWorkspace().then((result) => { setData(result); setForm((current) => ({ ...current, workId: current.workId || result.works[0]?.workId || '' })); setCompliance((current) => current.registrationNumber ? current : { registrationNumber: result.profile.registrationNumber || '', qualifications: result.profile.qualifications.join(', '), sectorCoverage: result.profile.sectorCoverage.join(', '), geographicCoverage: result.profile.geographicCoverage.join(', '), documentName: '', documentUrl: '' }); }).catch((err) => setError(err.message));
  useEffect(() => { load(); }, []);
  async function submit(event) { event.preventDefault(); setSaving(true); setError(''); try { await createAgencySubmission({ ...form, progress: form.progress === '' ? undefined : Number(form.progress), invoiceAmount: form.invoiceAmount === '' ? undefined : Number(form.invoiceAmount), proposedAmount: form.proposedAmount === '' ? undefined : Number(form.proposedAmount), proposedDurationDays: form.proposedDurationDays === '' ? undefined : Number(form.proposedDurationDays), coordinates: form.latitude && form.longitude ? { latitude: Number(form.latitude), longitude: Number(form.longitude) } : undefined, attachments: form.attachmentUrl ? [{ name: form.attachmentName || 'Supporting document', url: form.attachmentUrl }] : [] }); setForm((current) => ({ ...current, title: '', details: '', progress: '', invoiceAmount: '', proposedAmount: '', proposedDurationDays: '', attachmentName: '', attachmentUrl: '' })); await load(); setTab('submissions'); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  async function saveCompliance(event) { event.preventDefault(); setSaving(true); try { await updateAgencyProfile({ ...compliance, complianceDocuments: compliance.documentUrl ? [...profile.complianceDocuments, { name: compliance.documentName || 'Compliance document', url: compliance.documentUrl }] : profile.complianceDocuments }); setCompliance((current) => ({ ...current, documentName: '', documentUrl: '' })); await load(); } catch (err) { setError(err.message); } finally { setSaving(false); } }
  if (!data) return <main className="agency-workspace"><p className="agency-loading">{error || 'Loading agency workspace...'}</p></main>;
  const { profile, summary, works, tenders, submissions } = data;
  return <main className="agency-workspace"><header className="agency-workspace-head"><div><p>Agency Delivery Workspace</p><h1>{profile.agencyName}</h1><span>{profile.organization || 'Registered implementing agency'}</span></div><aside><b>{summary.avgProgress}%</b><small>Average reported progress</small></aside></header><nav className="agency-tabs">{[['overview', 'Overview'], ['tenders', 'Eligible Tenders'], ['works', 'Work Orders'], ['submit', 'Submit Update'], ['submissions', 'My Submissions'], ['compliance', 'Compliance Profile']].map(([id, label]) => <button key={id} className={tab === id ? 'active' : ''} onClick={() => setTab(id)}>{label}</button>)}</nav>{error && <p className="agency-workspace-error">{error}</p>}
    {tab === 'overview' && <><section className="agency-workspace-kpis">{[['Awarded works', summary.totalWorks], ['Completed', summary.completed], ['Delayed alerts', summary.delayed], ['High-risk findings', summary.highRisk], ['Sanctioned', money(summary.sanctioned)], ['Recorded expenditure', money(summary.expenditure)]].map(([label, value]) => <article key={label}><span>{label}</span><strong>{value}</strong></article>)}</section><section className="agency-workspace-grid"><article><h2>Compliance profile</h2><p><b>Registration:</b> {profile.registrationNumber || 'Not recorded'}</p><p><b>Qualifications:</b> {profile.qualifications.length ? profile.qualifications.join(', ') : 'Not recorded'}</p><p><b>Coverage:</b> {profile.geographicCoverage.length ? profile.geographicCoverage.join(', ') : 'Use profile to configure'}</p><p><b>Compliance documents:</b> {profile.complianceDocuments.length}</p></article><article><h2>Required actions</h2><p>Submit evidence and a clarification for any flagged assigned work.</p><p>Invoice, funding, and completion claims remain pending until an authorized government reviewer acts.</p><button onClick={() => setTab('submit')}>Create accountable submission</button></article></section></>}
    {tab === 'tenders' && <section className="agency-panel"><h2>Eligible tender opportunities</h2><p>Only public opportunities whose eligibility matches the recorded agency profile are shown. Competing bid data and tender decisions are not available.</p>{tenders.length ? tenders.map((tender) => <article className="agency-tender" key={tender._id}><div><b>{tender.reference}</b><h3>{tender.title}</h3><span>{tender.district}, {tender.state} · {tender.sector}</span></div><div><strong>{money(tender.estimatedAmount)}</strong><small>Deadline {new Date(tender.deadline).toLocaleDateString('en-IN')}</small><button onClick={() => { setForm((current) => ({ ...current, type: 'BID', workId: tender.reference, title: `Bid: ${tender.title}` })); setTab('submit'); }}>Prepare bid</button></div></article>) : <p className="agency-empty-state">No eligible tender opportunities are currently published.</p>}</section>}
    {tab === 'works' && <section className="agency-panel"><h2>Awarded work orders</h2><div className="agency-work-orders">{works.map((work) => <article key={work.workId}><div><b>{work.workId}</b><h3>{work.title}</h3><span>{work.district}, {work.state} · {work.sector}</span></div><div><span>{money(work.expenditureAmount)} of {money(work.sanctionedAmount)}</span><progress value={work.progress} max="100" /><b>{work.progress}% · {work.status}</b><button onClick={() => { setForm((current) => ({ ...current, workId: work.workId, type: 'PROGRESS_UPDATE', title: `Progress update: ${work.title}` })); setTab('submit'); }}>Report progress</button></div></article>)}</div></section>}
    {tab === 'submit' && <section className="agency-panel"><h2>Submit for authorized review</h2><p>Submissions create an audit record. They do not amend work progress, payments, awards, or risk outcomes without government review.</p><form className="agency-submission-form" onSubmit={submit}><label>Submission type<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}>{TYPES.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>{form.type !== 'BID' && <label>Assigned work<select value={form.workId} onChange={(e) => setForm({ ...form, workId: e.target.value })}>{works.map((work) => <option key={work.workId}>{work.workId}</option>)}</select></label>}<label>Subject<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label>Details<textarea required value={form.details} onChange={(e) => setForm({ ...form, details: e.target.value })} placeholder="Provide clear factual information for review." /></label>{['PROGRESS_UPDATE', 'GEO_EVIDENCE', 'COMPLETION_CERTIFICATE'].includes(form.type) && <label>Progress (%)<input type="number" min="0" max="100" value={form.progress} onChange={(e) => setForm({ ...form, progress: e.target.value })} /></label>}{form.type === 'INVOICE' && <label>Invoice amount (lakhs)<input type="number" min="0" value={form.invoiceAmount} onChange={(e) => setForm({ ...form, invoiceAmount: e.target.value })} /></label>}{form.type === 'BID' && <><label>Proposed amount (lakhs)<input type="number" min="0" value={form.proposedAmount} onChange={(e) => setForm({ ...form, proposedAmount: e.target.value })} /></label><label>Delivery duration (days)<input type="number" min="1" value={form.proposedDurationDays} onChange={(e) => setForm({ ...form, proposedDurationDays: e.target.value })} /></label></>}<label>Evidence document name<input value={form.attachmentName} onChange={(e) => setForm({ ...form, attachmentName: e.target.value })} /></label><label>Evidence document URL<input type="url" value={form.attachmentUrl} onChange={(e) => setForm({ ...form, attachmentUrl: e.target.value })} placeholder="https://..." /></label><button disabled={saving}>{saving ? 'Submitting...' : 'Submit for review'}</button></form></section>}
    {tab === 'submissions' && <section className="agency-panel"><h2>Submission history</h2>{submissions.length ? <table className="agency-submissions"><thead><tr><th>Type</th><th>Reference</th><th>Submitted</th><th>Status</th><th>Revision</th></tr></thead><tbody>{submissions.map((item) => <tr key={item._id}><td>{item.type.replaceAll('_', ' ')}</td><td><b>{item.title}</b><small>{item.workId || 'Tender bid'}</small></td><td>{new Date(item.createdAt).toLocaleString('en-IN')}</td><td><span>{item.status.replaceAll('_', ' ')}</span></td><td>{item.revision} {['DRAFT', 'SUBMITTED', 'REQUESTED_CHANGES'].includes(item.status) && <button onClick={() => { reviseAgencySubmission(item._id, { details: item.details }).then(load).catch((err) => setError(err.message)); }}>Resubmit</button>}</td></tr>)}</tbody></table> : <p className="agency-empty-state">No agency submissions have been recorded.</p>}</section>}
    {tab === 'compliance' && <section className="agency-panel"><h2>Agency qualifications and compliance</h2><form className="agency-submission-form" onSubmit={saveCompliance}><label>Registration number<input value={compliance.registrationNumber} onChange={(e) => setCompliance({ ...compliance, registrationNumber: e.target.value })} /></label><label>Qualifications (comma separated)<input value={compliance.qualifications} onChange={(e) => setCompliance({ ...compliance, qualifications: e.target.value })} /></label><label>Sector coverage (comma separated)<input value={compliance.sectorCoverage} onChange={(e) => setCompliance({ ...compliance, sectorCoverage: e.target.value })} /></label><label>Geographic coverage (comma separated)<input value={compliance.geographicCoverage} onChange={(e) => setCompliance({ ...compliance, geographicCoverage: e.target.value })} /></label><label>Compliance document name<input value={compliance.documentName} onChange={(e) => setCompliance({ ...compliance, documentName: e.target.value })} /></label><label>Compliance document URL<input type="url" value={compliance.documentUrl} onChange={(e) => setCompliance({ ...compliance, documentUrl: e.target.value })} /></label><button disabled={saving}>{saving ? 'Saving...' : 'Save compliance profile'}</button></form></section>}
  </main>;
}
