import React, { useEffect, useState } from 'react';
import { getAgencyRisk } from '../services/api.js';
import { downloadCsv } from '../utils/download.js';

export default function AgencyRisk() {
  const [data, setData] = useState(null); const [query, setQuery] = useState('');
  useEffect(() => { getAgencyRisk().then(setData).catch(() => setData(null)); }, []);
  if (!data) return <main className="agency-page loading-risk">Loading implementing agency risk...</main>;
  const agencies = data.agencies.filter((agency) => `${agency.agency} ${agency.state}`.toLowerCase().includes(query.toLowerCase()));
  const { summary } = data;
  const downloadReport = () => downloadCsv('agency-risk-report.csv', ['Agency', 'State', 'Total Works', 'Completed', 'Delayed', 'Average Delay (Months)', 'Cost Deviation (%)', 'Incomplete (%)', 'Risk Level', 'Risk Score'], agencies.map((agency) => [agency.agency, agency.state, agency.totalWorks, agency.completed, agency.delayed, agency.averageDelay, agency.costDeviation, agency.incompletePercent, agency.riskLevel, agency.riskScore]));
  return <main className="agency-page"><header className="agency-top"><input placeholder="Search work ID, district, agency..." /><span>FY 24-25</span></header><section className="agency-content"><header className="agency-title"><div><h1>Implementing Agency Risk</h1><p>Compare agency performance, delays, cost deviations and incomplete works across the MPLADS network.</p></div><div><button onClick={downloadReport}>Export Report</button><button className="agency-filter">Filters</button></div></header><section className="agency-kpis"><article><p>Total Agencies</p><strong>{summary.totalAgencies.toLocaleString('en-IN')}</strong><small>Active nationwide</small></article><article className="risk"><p>High-Risk Agencies</p><strong>{summary.highRiskAgencies}</strong><small>Requires priority review</small></article><article><p>Average Delay</p><strong>{summary.averageDelay} <b>Mo</b></strong><i><b /></i></article><article><p>Avg Cost Deviation</p><strong className="risk-text">{summary.averageCostDeviation > 0 ? '+' : ''}{summary.averageCostDeviation}%</strong><small>Across all monitored works</small></article></section><section className="agency-table"><header><label><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search Agency Name..." /></label><div><button>All States⌄</button><button>All Risks⌄</button><button>All Types⌄</button></div></header><table><thead><tr><th>Agency Name</th><th>State</th><th>Total Works</th><th>Completed</th><th>Delayed</th><th>Avg Delay</th><th>Cost Overrun</th><th>Incomplete %</th><th>Risk Score</th></tr></thead><tbody>{agencies.map((agency) => <tr key={`${agency.agency}-${agency.state}`}><td><strong>{agency.agency}</strong></td><td>{agency.state}</td><td>{agency.totalWorks}</td><td>{agency.completed}</td><td className={agency.delayed ? 'risk-text' : ''}>{agency.delayed}</td><td>{agency.averageDelay} Mo</td><td className={agency.costDeviation > 0 ? 'risk-text' : ''}>{agency.costDeviation > 0 ? '+' : ''}{agency.costDeviation}%</td><td>{agency.incompletePercent}% <i className="agency-progress"><b style={{ width: `${agency.incompletePercent}%` }} /></i></td><td><span className={`agency-level ${agency.riskLevel}`}>{agency.riskLevel}</span> <b className={`agency-score ${agency.riskLevel}`}>{agency.riskScore}</b></td></tr>)}</tbody></table></section></section></main>;
}
