import React, { useEffect, useState } from 'react';
import { getDataRefreshOverview } from '../services/api.js';

function formatDate(value) { return value ? new Date(value).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }) : 'Not available'; }

export default function DataRefresh() {
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [refreshing, setRefreshing] = useState(false);
  const load = async () => { setRefreshing(true); setError(''); try { setData(await getDataRefreshOverview()); } catch { setError('Unable to load source health. Please try again.'); } finally { setRefreshing(false); } };
  useEffect(() => { load(); }, []);
  if (error) return <main className="refresh-page refresh-loading"><p>{error}</p><button onClick={load}>Retry</button></main>;
  if (!data) return <main className="refresh-page refresh-loading">Loading data refresh health...</main>;
  const { health, sources } = data;
  return <main className="refresh-page"><header className="refresh-top"><div><p>Data Operations</p><h1>Data Refresh Dashboard</h1><span>Monitor source availability, import quality and dataset health.</span></div><button onClick={load} disabled={refreshing}>{refreshing ? 'Refreshing...' : 'Refresh Status'}</button></header><section className="refresh-content"><section className="health-banner"><div><p>Dataset health</p><h2 className={health.status}>{health.status === 'healthy' ? 'Operational' : 'Attention required'}</h2><span>{health.healthySources} of {health.totalSources} sources are healthy.</span></div><small>Last synchronized<br /><b>{formatDate(health.lastSync)}</b></small></section><section className="refresh-kpis"><article><p>Source Status</p><strong>{health.healthySources}/{health.totalSources}</strong><span>Healthy sources</span></article><article><p>Imported Records</p><strong>{health.workCount.toLocaleString('en-IN')}</strong><span>Works available to APIs</span></article><article><p>Failed Rows</p><strong className={health.failedRows ? 'warning' : ''}>{health.failedRows.toLocaleString('en-IN')}</strong><span>Latest import runs</span></article><article><p>Refresh Mode</p><strong>Manual</strong><span>CSV import pipeline</span></article></section><section className="source-health"><header><div><h2>Source Refresh Status</h2><p>Each source is checked against its indexed MongoDB records.</p></div><span>{sources.length} sources monitored</span></header><div className="source-table"><table><thead><tr><th>Data Source</th><th>Status</th><th>Import Count</th><th>Failed Rows</th><th>Last Sync</th><th>Health Detail</th></tr></thead><tbody>{sources.map((source) => <tr key={source.key}><td><strong>{source.label}</strong><small>{source.file}</small></td><td><span className={`source-status ${source.status}`}>{source.status}</span></td><td>{source.rowCount.toLocaleString('en-IN')}</td><td className={source.failedRows ? 'failed-rows' : ''}>{source.failedRows.toLocaleString('en-IN')}</td><td>{formatDate(source.lastSync)}</td><td>{source.message}</td></tr>)}</tbody></table></div></section><section className="refresh-notes"><h2>Data Health Notes</h2><p>Source rows are retained in the dataset store. Completed and recommended work records are also indexed into the operational works collection used by the dashboard, risk, map, analytics and reporting APIs.</p></section></section></main>;
}
