import React, { useEffect, useState } from 'react';
import { BarChart, Bar, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CircleMarker, MapContainer, Popup, TileLayer, useMap } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import { getPublicAnalytics, getPublicFilters, getPublicMap, getPublicOverview, getPublicWork, getPublicWorks } from '../services/api.js';

const formatNumber = (value) => new Intl.NumberFormat('en-IN').format(Math.round(value || 0));
const formatAmount = (value) => `Rs ${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 1 })} L`;
const riskColors = { high: '#b42318', medium: '#b7791f', low: '#356a50' };
const pieColors = ['#b42318', '#b7791f', '#356a50', '#8793a5'];

function MapFocus({ marker }) {
  const map = useMap();
  useEffect(() => { if (marker?.coordinates) map.flyTo([marker.coordinates.latitude, marker.coordinates.longitude], 8, { duration: 0.7 }); }, [marker, map]);
  return null;
}

function PublicMap({ markers, selected, onSelect }) {
  const mappedMarkers = markers.filter((work) => Number.isFinite(work.coordinates?.latitude) && Number.isFinite(work.coordinates?.longitude));
  if (!mappedMarkers.length) return <div className="public-map-empty"><b>No published high-risk locations are available.</b><span>Map points will appear when public monitoring data is available.</span></div>;
  return <div className="public-map"><MapContainer center={[22.5, 79]} zoom={4} scrollWheelZoom className="public-leaflet-map"><MapFocus marker={selected} /><TileLayer attribution="&copy; OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />
    {markers.filter((work) => work.coordinates?.latitude && work.coordinates?.longitude).map((work) => <CircleMarker key={work.workId} center={[work.coordinates.latitude, work.coordinates.longitude]} radius={selected?.workId === work.workId ? 11 : 7} pathOptions={{ color: '#7f1d1d', fillColor: '#d92d20', fillOpacity: 0.75 }} eventHandlers={{ click: () => onSelect(work) }}><Popup><strong>{work.title}</strong><br />{work.district}, {work.state}<br />Risk score: {work.riskScore}/100</Popup></CircleMarker>)}
  </MapContainer></div>;
}

function DownloadButton({ works }) {
  function download() {
    const rows = [['Work ID', 'Title', 'State', 'District', 'Sector', 'Sanctioned (Lakhs)', 'Expenditure (Lakhs)', 'Progress', 'Status', 'Risk level'], ...works.map((w) => [w.workId, w.title, w.state, w.district, w.sector, w.sanctionedAmount, w.expenditureAmount, `${w.progress}%`, w.status, w.riskLevel])];
    const csv = rows.map((row) => row.map((value) => `"${String(value ?? '').replaceAll('"', '""')}"`).join(',')).join('\n');
    const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }));
    const link = document.createElement('a'); link.href = url; link.download = 'prahari-public-works.csv'; link.click(); URL.revokeObjectURL(url);
  }
  return <button type="button" className="public-button secondary" onClick={download}>Download data</button>;
}

export default function PublicViewer({ page, onNavigate, onLogin }) {
  const [overview, setOverview] = useState(null); const [filters, setFilters] = useState({ states: [], districts: [], sectors: [] });
  const [works, setWorks] = useState([]); const [pagination, setPagination] = useState(null); const [mapData, setMapData] = useState([]); const [analytics, setAnalytics] = useState(null);
  const [selectedWork, setSelectedWork] = useState(null); const [search, setSearch] = useState(''); const [state, setState] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { Promise.all([getPublicOverview(), getPublicFilters(), getPublicMap(), getPublicAnalytics()]).then(([o, f, m, a]) => { setOverview(o); setFilters(f); setMapData(m.markers); setAnalytics(a); }).catch((err) => setError(err.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (page !== 'works') return; const timer = setTimeout(() => { getPublicWorks({ search, state, limit: 20 }).then((data) => { setWorks(data.works); setPagination(data.pagination); }).catch((err) => setError(err.message)); }, 220); return () => clearTimeout(timer); }, [page, search, state]);
  useEffect(() => { if (!selectedWork?.workId) return; getPublicWork(selectedWork.workId).then((data) => setSelectedWork(data.work)).catch(() => undefined); }, [selectedWork?.workId]);

  const navItems = [['overview', 'Overview'], ['works', 'Works'], ['map', 'Risk Map'], ['analytics', 'Analytics'], ['about', 'About Data']];
  const visibleWorks = works.length ? works : mapData;
  return <div className="public-site">
    <a className="public-skip" href="#public-content">Skip to content</a>
    <header className="public-header"><button className="public-brand" onClick={() => onNavigate('overview')}><img src="/prahari-ai-logo.png" alt="Prahari AI" /><span><b>PRAHARI</b><small>Public Monitoring Portal</small></span></button><nav aria-label="Public navigation">{navItems.map(([id, label]) => <button key={id} className={page === id ? 'active' : ''} onClick={() => onNavigate(id)}>{label}</button>)}</nav><button className="public-button login" onClick={onLogin}>Official login</button></header>
    {error && <p className="public-error">Data service unavailable: {error}</p>}
    <main id="public-content" className="public-content">
      {loading ? <section className="public-loading"><b>PRAHARI Public Viewer</b><p>Loading national monitoring data...</p></section> : null}
      {!loading && page === 'overview' && <>
        <section className="public-hero"><p className="eyebrow">MPLADS Public Information Portal</p><h1>Public monitoring of development works across India.</h1><p>Explore approved MPLADS work information, implementation status, fund utilization, and aggregated risk indicators.</p><div><button className="public-button" onClick={() => onNavigate('works')}>Explore works</button><button className="public-button secondary" onClick={() => onNavigate('map')}>View risk map</button></div></section>
        <section className="public-stat-grid" aria-label="National monitoring summary"><Stat label="Total works" value={formatNumber(overview?.totalWorks)} /><Stat label="Sanctioned value" value={formatAmount(overview?.totalSanctioned)} /><Stat label="Recorded expenditure" value={formatAmount(overview?.totalExpenditure)} /><Stat label="Fund utilization" value={`${overview?.utilization || 0}%`} /></section>
        <section className="public-grid two"><article className="public-card"><div className="card-heading"><div><p className="eyebrow">National overview</p><h2>High-risk work concentration</h2></div><button className="text-button" onClick={() => onNavigate('analytics')}>View analytics</button></div><ResponsiveContainer width="100%" height={270}><BarChart data={overview?.stateRisk || []} layout="vertical" margin={{ left: 12 }}><XAxis type="number" hide /><YAxis dataKey="state" type="category" width={110} tick={{ fontSize: 12 }} /><Tooltip /><Bar dataKey="highRiskWorks" name="High-risk works" fill="#a63c32" radius={[0, 3, 3, 0]} /></BarChart></ResponsiveContainer></article><article className="public-card"><p className="eyebrow">Risk distribution</p><h2>Work risk categories</h2><ResponsiveContainer width="100%" height={270}><PieChart><Pie data={overview?.riskDistribution || []} dataKey="value" nameKey="name" innerRadius={60} outerRadius={96} paddingAngle={2}>{(overview?.riskDistribution || []).map((entry, index) => <Cell key={entry.name} fill={riskColors[entry.name] || pieColors[index]} />)}</Pie><Tooltip /><Legend /></PieChart></ResponsiveContainer></article></section>
        <section className="public-card public-notice"><h2>How to use this information</h2><p>Risk indicators highlight records that may benefit from additional monitoring. They are not findings of wrongdoing. Values are based on the latest available MPLADS data.</p><span>Last refreshed: {new Date(overview?.lastUpdated).toLocaleString('en-IN')}</span></section>
      </>}
      {!loading && page === 'works' && <><section className="public-page-heading"><p className="eyebrow">Public work directory</p><h1>Explore MPLADS works</h1><p>Search published work records across India. Financial values are shown in lakhs.</p></section><section className="public-filter-bar"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search work ID, title, district or sector" aria-label="Search works" /><select value={state} onChange={(event) => setState(event.target.value)}><option value="">India - all states</option>{filters.states.map((item) => <option key={item}>{item}</option>)}</select><DownloadButton works={visibleWorks} /></section><section className="public-work-table"><div className="public-table-caption">{formatNumber(pagination?.total)} published works matching the selected criteria</div><div className="table-scroll"><table><thead><tr><th>Work</th><th>Location</th><th>Financial status</th><th>Progress</th><th>Risk indicator</th></tr></thead><tbody>{works.map((work) => <tr key={work.workId} onClick={() => setSelectedWork(work)} tabIndex="0"><td><b>{work.title}</b><small>{work.workId}</small></td><td>{work.district}<small>{work.state}</small></td><td>{formatAmount(work.expenditureAmount)}<small>of {formatAmount(work.sanctionedAmount)}</small></td><td><Progress value={work.progress} /><small>{work.status}</small></td><td><span className={`public-risk ${work.riskLevel}`}>{work.riskLevel} {work.riskScore}/100</span></td></tr>)}</tbody></table></div></section>{selectedWork && <WorkPanel work={selectedWork} onClose={() => setSelectedWork(null)} />}</>}
      {!loading && page === 'map' && <><section className="public-page-heading"><p className="eyebrow">Geographic monitoring</p><h1>High-risk zones</h1><p>Only published high-risk work locations are displayed. Select a point to view its public record.</p></section><section className="public-map-layout"><PublicMap markers={mapData} selected={selectedWork} onSelect={setSelectedWork} /><aside className="public-card map-list"><h2>Priority locations</h2><p className="map-count">{formatNumber(mapData.length)} published high-risk locations</p>{mapData.slice(0, 7).map((work) => <button key={work.workId} onClick={() => setSelectedWork(work)}><span><b>{work.district}</b><small>{work.state}</small></span><strong>{work.riskScore}</strong></button>)}{!mapData.length && <p className="map-empty-copy">No map records were returned by the data service.</p>}</aside></section>{selectedWork && <WorkPanel work={selectedWork} onClose={() => setSelectedWork(null)} />}</>}
      {!loading && page === 'analytics' && <><section className="public-page-heading"><p className="eyebrow">National trends</p><h1>Monitoring analytics</h1><p>Aggregated analysis of published MPLADS works. Filtered operational data and individual review records are not displayed.</p></section><section className="public-grid two"><ChartCard title="High-risk works by state"><BarChart data={analytics?.stateRisk || []}><XAxis dataKey="state" tick={{ fontSize: 11 }} /><YAxis /><Tooltip /><Bar dataKey="highRisk" fill="#a63c32" /></BarChart></ChartCard><ChartCard title="Works by implementation status"><PieChart><Pie data={analytics?.status || []} dataKey="value" nameKey="name" outerRadius={90}>{(analytics?.status || []).map((entry, index) => <Cell key={entry.name} fill={pieColors[index]} />)}</Pie><Tooltip /><Legend /></PieChart></ChartCard><ChartCard title="Works by sector"><BarChart data={analytics?.sector || []}><XAxis dataKey="name" tick={{ fontSize: 10 }} interval={0} /><YAxis /><Tooltip /><Bar dataKey="value" fill="#294d6a" /></BarChart></ChartCard><article className="public-card"><p className="eyebrow">Data interpretation</p><h2>Transparent by design</h2><p>Charts use aggregate records and refresh as published datasets are imported. Risk category is a monitoring signal, not a legal conclusion.</p><button className="public-button secondary" onClick={() => onNavigate('about')}>Read methodology</button></article></section></>}
      {!loading && page === 'about' && <><section className="public-page-heading"><p className="eyebrow">Transparency</p><h1>About the public data</h1><p>Information is published to support civic awareness while protecting official users and active review processes.</p></section><section className="public-grid two"><article className="public-card"><h2>Published information</h2><ul><li>Work location, sector, status and progress</li><li>Sanctioned amount and recorded expenditure</li><li>Aggregated risk category and monitoring signals</li><li>Dataset refresh information and national trends</li></ul></article><article className="public-card"><h2>Protected information</h2><ul><li>Official user accounts and contact information</li><li>Internal review assignments and evidence</li><li>Appeals, audit records and operational notes</li><li>Unpublished or restricted work records</li></ul></article></section><section className="public-card public-notice"><h2>Data quality and limitation</h2><p>Figures reflect available source data and may change after validation or later reporting. Public risk information is provided for transparency and should be read alongside official documentation.</p><p><b>Current public coverage:</b> {formatNumber(overview?.totalWorks)} work records across India.</p></section></>}
    </main><footer className="public-footer"><span>PRAHARI Public Monitoring Portal</span><span>For information and transparency purposes</span><button onClick={onLogin}>Official access</button></footer>
  </div>;
}

function Stat({ label, value }) { return <article className="public-stat"><span>{label}</span><strong>{value}</strong></article>; }
function Progress({ value }) { return <span className="public-progress"><i style={{ width: `${Math.min(100, Math.max(0, value || 0))}%` }} /><b>{value || 0}%</b></span>; }
function ChartCard({ title, children }) { return <article className="public-card"><h2>{title}</h2><ResponsiveContainer width="100%" height={270}>{children}</ResponsiveContainer></article>; }
function WorkPanel({ work, onClose }) { return <section className="public-work-panel" aria-live="polite"><button aria-label="Close work detail" onClick={onClose}>×</button><p className="eyebrow">Published work record</p><h2>{work.title}</h2><p>{work.workId} · {work.district}, {work.state}</p><div><span>Sanctioned <b>{formatAmount(work.sanctionedAmount)}</b></span><span>Expenditure <b>{formatAmount(work.expenditureAmount)}</b></span><span>Progress <b>{work.progress}%</b></span><span>Risk <b className={work.riskLevel}>{work.riskLevel} ({work.riskScore}/100)</b></span></div><p className="disclaimer">Risk indicators are informational and are not a finding of wrongdoing.</p></section>; }
