import React, { useEffect, useState } from 'react';
import Logo from './Logo.jsx';
import { getWork, markWorkUnderReview } from '../services/api.js';

function Icon({ name }) { const paths = { back: <path d="m14 5-7 7 7 7M8 12h10" />, shield: <><path d="M12 3.5c-2.2 1.7-4.7 2.5-7 2.8v5.1c0 4.1 2.6 7.6 7 9.1 4.4-1.5 7-5 7-9.1V6.3c-2.3-.3-4.8-1.1-7-2.8Z" /><path d="m9.1 12 2 2 3.8-4" /></>, robot: <><rect x="5" y="7" width="14" height="12" rx="2" /><path d="M12 4v3M8.5 12h.1M15.4 12h.1M9 16h6" /></>, chart: <><path d="M4 20V4M4 20h17M8 16v-4M13 16V7M18 16v-7" /></> }; return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>; }
const tone = { danger: '#c51d25', warning: '#352500', neutral: '#0b1d3a' };

export default function WorkInvestigation({ workId, user, onNavigate, onSignOut }) {
  const [data, setData] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { let active = true; getWork(workId).then((result) => active && setData(result)).catch((requestError) => active && setError(requestError.message)); return () => { active = false; }; }, [workId]);
  if (error) return <main className="investigation-error"><h1>{error}</h1><button onClick={() => onNavigate('works')}>Back to Works</button></main>;
  if (!data) return <main className="investigation-loading">Loading work investigation...</main>;
  const { work, assessment } = data;
  const review = async () => { setSaving(true); try { const result = await markWorkUnderReview(work.workId); setData((current) => ({ ...current, work: result.work })); } finally { setSaving(false); } };
  return <main className="investigation-page"><header className="dashboard-header"><div className="dashboard-brand"><Logo /><div><strong>PRAHARI</strong><span>Institutional Oversight</span></div></div><div className="header-actions"><button>FY 24-25</button><span className="avatar">{user.name.charAt(0)}</span></div></header><div className="command-search"><span>⌕</span><input placeholder="Search work ID, district, agency..." /></div>
    <section className="investigation-content"><div className="breadcrumbs">Dashboard　›　Works Explorer　›　<strong>Work Investigation</strong></div><section className="investigation-head"><div><h1>{work.title}</h1><p><span className="investigation-id">{work.workId}</span><span className="status ongoing">{work.status}</span></p><small>{work.district}, {work.state}　|　Executing Agency: {work.agency}</small></div><aside className="score-card"><div><p>AI Risk Score</p><strong>{assessment.score}</strong><b>/100</b></div><div><span className={`score-dot ${assessment.level}`} /> <strong>{assessment.level} risk</strong><p>Requires immediate review</p></div><footer><button>Generate Report</button><button className="review-button" onClick={review} disabled={saving || work.underReview}>{work.underReview ? 'Under Review' : saving ? 'Saving...' : 'Mark Under Review'}</button></footer></aside></section>
      <div className="investigation-grid"><section><div className="investigation-metrics"><article><p>Est. Cost</p><strong>INR {assessment.estimatedCost} L</strong></article><article><p>Sanctioned</p><strong>INR {work.sanctionedAmount} L</strong></article><article className="overrun"><p>Expenditure</p><strong>INR {work.expenditureAmount} L</strong><small>{assessment.expenditureRatio}%</small></article><article><p>Physical Progress</p><strong>{work.progress}%</strong><i><b style={{ width: `${work.progress}%` }} /></i></article></div><article className="assessment-card"><header><span><Icon name="robot" /> AI Risk Assessment</span><b>Why was this work flagged?</b></header><div className="anomaly"><span><Icon name="chart" /></span><section><h2>Cost Anomaly Detected <b>High Risk</b></h2><p>Significant cost deviation compared to peer benchmark. Model indicates a variance from expected norm.</p><small>Isolation Forest　 Peer Avg: INR {assessment.estimatedCost} L | Actual: INR {work.expenditureAmount} L</small></section></div><div className="anomaly"><span><Icon name="chart" /></span><section><h2>Payment-Progress Mismatch <b>High Risk</b></h2><p>Expenditure booking ({assessment.expenditureRatio}% of sanctioned amount) is disproportionate to recorded physical progress ({work.progress}%).</p><div className="comparison"><i style={{ width: `${work.progress}%` }}>Progress {work.progress}%</i><i style={{ width: `${Math.min(assessment.expenditureRatio, 100)}%` }}>Payments {assessment.expenditureRatio}%</i></div></section></div><div className="assessment-bottom"><article><h2>Execution Delay</h2><p>Work is currently lagging against scheduled timeline. Expected completion requires field verification.</p></article><article><h2>Similarity Warning</h2><p>NLP model found similarity with other works executed by the same agency in adjacent blocks.</p></article></div></article></section><aside className="investigation-side"><article className="vectors"><h2><Icon name="chart" /> Risk Vectors</h2>{assessment.vectors.map((vector) => <div key={vector.label}><p>{vector.label}<b style={{ color: tone[vector.tone] }}>{vector.score}/100</b></p><i><b style={{ width: `${vector.score}%`, background: tone[vector.tone] }} /></i></div>)}</article><article className="executive"><h2>Executive Summary</h2><p>{assessment.summary}</p><hr /><small>Recommended actions</small><ul><li>Initiate physical inspection to verify progress claim.</li><li>Audit payment tranches and supporting documents.</li></ul></article><dl><div><dt>Model Version</dt><dd>AnomalyEngine_v1.4</dd></div><div><dt>Analysis Time</dt><dd>Today, 08:42 AM</dd></div><div><dt>Confidence</dt><dd>94.2%</dd></div></dl></aside></div></section>
    </main>;
}
