import React, { useEffect, useState } from 'react';
import Logo from './Logo.jsx';
import { downloadCsv } from '../utils/download.js';
import { getFilterOptions, getWorks } from '../services/api.js';

const fallbackWorks = [
  { risk: 'high', id: 'MPL-WB-25-01284', title: 'Construction of Community Hall', alert: 'Cost Overrun Detected', location: 'Howrah', state: 'West Bengal', agency: 'Zilla Parishad', sanctioned: 'INR 25.00 L', expenditure: 'INR 31.40 L', progress: 72, status: 'Ongoing', score: 89 },
  { risk: 'medium', id: 'MPL-MH-24-08832', title: 'Solar Street Lights Installation', alert: 'Delayed by 4 months', location: 'Pune', state: 'Maharashtra', agency: 'Gram Panchayat', sanctioned: 'INR 12.50 L', expenditure: 'INR 8.20 L', progress: 45, status: 'Ongoing', score: 54 },
  { risk: 'low', id: 'MPL-KA-23-04112', title: 'Procurement of Ambulances', alert: '', location: 'Mysuru', state: 'Karnataka', agency: 'Dept of Health', sanctioned: 'INR 45.00 L', expenditure: 'INR 44.80 L', progress: 100, status: 'Completed', score: 12 },
  { risk: 'high', id: 'MPL-UP-25-09941', title: 'Deepening of Village Pond', alert: 'Potential Duplicate Sanction', location: 'Varanasi', state: 'Uttar Pradesh', agency: 'Irrigation Dept', sanctioned: 'INR 15.00 L', expenditure: 'INR 0.00 L', progress: 0, status: 'Sanctioned', score: 94 },
  { risk: 'low', id: 'MPL-TN-24-11205', title: 'Construction of Additional Classroom', alert: '', location: 'Madurai', state: 'Tamil Nadu', agency: 'PWD', sanctioned: 'INR 35.00 L', expenditure: 'INR 28.00 L', progress: 80, status: 'Ongoing', score: 18 },
];

function Icon({ name }) { const paths = { home: <path d="m3.5 10 8.5-6.5 8.5 6.5v9.5H14v-5H10v5H3.5Z" />, works: <><path d="M5 7h14M5 12h14M5 17h14" /><circle cx="3" cy="7" r=".8" fill="currentColor" /><circle cx="3" cy="12" r=".8" fill="currentColor" /><circle cx="3" cy="17" r=".8" fill="currentColor" /></>, risk: <><path d="M12 3 21 20H3L12 3Z" /><path d="M12 9v4M12 16v.2" /></>, ai: <path d="m14.5 4-6.3 8.2 4.4 1.4-3 6.4 6.4-8.6-4.2-1.1Z" />, more: <><circle cx="5" cy="12" r="1" fill="currentColor" /><circle cx="12" cy="12" r="1" fill="currentColor" /><circle cx="19" cy="12" r="1" fill="currentColor" /></>, search: <><circle cx="10.5" cy="10.5" r="5.5" /><path d="m15 15 4 4" /></> }; return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]}</svg>; }
function formatLakh(value) { return `INR ${Number(value || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} L`; }

export default function WorksExplorer({ user, works: apiWorks, onSignOut, onNavigate, onOpenWork }) {
  const [query, setQuery] = useState('');
  const [state, setState] = useState(''); const [status, setStatus] = useState(''); const [risk, setRisk] = useState(''); const [options, setOptions] = useState({ states: [] }); const [filteredApiWorks, setFilteredApiWorks] = useState(null);
  useEffect(() => { getFilterOptions().then(setOptions).catch(() => setOptions({ states: [] })); }, []);
  useEffect(() => { if (!state && !status && !risk && !query) { setFilteredApiWorks(null); return; } const timeout = window.setTimeout(() => { getWorks({ search: query, state, status, risk }).then((data) => setFilteredApiWorks(data.works)).catch(() => setFilteredApiWorks([])); }, 250); return () => window.clearTimeout(timeout); }, [query, state, status, risk]);
  const sourceWorks = filteredApiWorks || apiWorks;
  const displayWorks = sourceWorks?.length ? sourceWorks.map((work) => ({ risk: work.riskLevel, id: work.workId, title: work.title, alert: work.alert, location: work.district, state: work.state, agency: work.agency, sanctioned: formatLakh(work.sanctionedAmount), expenditure: work.expenditureSource === 'UNAVAILABLE' && !work.expenditureAmount ? 'Not reported' : formatLakh(work.expenditureAmount), progress: work.progress, status: work.status, score: work.riskScore })) : (filteredApiWorks ? [] : fallbackWorks);
  const visibleWorks = displayWorks.filter((work) => `${work.id} ${work.title} ${work.location} ${work.agency}`.toLowerCase().includes(query.toLowerCase()));
  const downloadWorks = () => downloadCsv('works-explorer.csv', ['Work ID', 'Title', 'State', 'District', 'Agency', 'Sanctioned', 'Expenditure', 'Progress', 'Status', 'Risk Level', 'Risk Score'], visibleWorks.map((work) => [work.id, work.title, work.state, work.location, work.agency, work.sanctioned, work.expenditure, `${work.progress}%`, work.status, work.risk, work.score]));
  return <main className="works-page"><header className="dashboard-header"><div className="dashboard-brand"><Logo /><div><strong>PRAHARI</strong><span>Institutional Oversight</span></div></div><div className="header-actions"><button>FY 24-25</button><span className="avatar">{user.name.charAt(0)}</span></div></header><div className="command-search"><Icon name="search" /><input placeholder="Search work ID, district, agency..." value={query} onChange={(event) => setQuery(event.target.value)} /></div>
    <section className="works-hero"><p>Directory <b>/</b> All Data</p><div><section><h1>Works Explorer</h1><span>Search, filter, and analyze the national registry of MPLADS projects across states, districts, and administrative bodies.</span></section><label><Icon name="search" /><input placeholder="Search Work ID, district, agency or description..." value={query} onChange={(event) => setQuery(event.target.value)} /></label></div></section>
    <section className="works-content"><div className="filter-bar"><div className="filters"><button>FY 2024-2025</button><select value={state} onChange={(event) => setState(event.target.value)}><option value="">India (All States)</option>{options.states.map((item) => <option key={item}>{item}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Any Status</option>{['Sanctioned', 'Ongoing', 'Completed', 'Delayed'].map((item) => <option key={item}>{item}</option>)}</select><select value={risk} onChange={(event) => setRisk(event.target.value)}><option value="">All Risk Levels</option>{['high', 'medium', 'low'].map((item) => <option key={item} value={item}>{item[0].toUpperCase()}{item.slice(1)}</option>)}</select><button className="apply-filter" onClick={() => { setState(''); setStatus(''); setRisk(''); setQuery(''); }}>Reset</button></div><p><strong>{visibleWorks.length}</strong> works matching criteria <span>{state || 'India'} ×</span></p></div><section className="work-stat-grid"><article><p>Total Works</p><strong>{visibleWorks.length}</strong></article><article className="danger"><p>High Risk</p><strong>{visibleWorks.filter((work) => work.risk === 'high').length}</strong></article><article className="warning"><p>Delayed</p><strong>{visibleWorks.filter((work) => work.status === 'Delayed').length}</strong></article><article><p>Potential Dupes</p><strong>{visibleWorks.filter((work) => /duplicate/i.test(work.alert)).length}</strong></article></section>
      <div className="table-wrap"><table><thead><tr><th>Risk</th><th>Work ID</th><th>Description</th><th>Location</th><th>Agency</th><th>Sanctioned</th><th>Expenditure</th><th>Progress</th><th>Status</th><th>Score</th></tr></thead><tbody>{visibleWorks.map((work) => <tr key={work.id}><td><i className={`risk-dot ${work.risk}`} /></td><td className="work-id">{work.id}</td><td><button className="work-link" onClick={() => onOpenWork(work.id)}><strong>{work.title}</strong>{work.alert && <small className={work.risk}>{work.alert}</small>}</button></td><td>{work.location}<small>{work.state}</small></td><td>{work.agency}</td><td>{work.sanctioned}</td><td className={work.risk === 'high' ? 'expense-high' : ''}>{work.expenditure}</td><td><span className="progress-cell"><i><b style={{ width: `${work.progress}%` }} /></i>{work.progress}%</span></td><td><span className={`status ${work.status.toLowerCase()}`}>{work.status}</span></td><td className={`score ${work.risk}`}>{work.score}</td></tr>)}</tbody></table><footer><span>Rows per page: <b>25⌄</b></span><span>1-25 of 12,482 &nbsp; <b>‹　›</b></span><button onClick={downloadWorks}>Download CSV</button></footer></div></section>
  </main>;
}
