import cors from 'cors';
import express from 'express';
import { env } from './config/env.js';
import { errorHandler, notFound } from './middleware/errorHandler.js';
import { authRouter } from './routes/authRoutes.js';
import { dashboardRouter } from './routes/dashboardRoutes.js';
import { worksRouter } from './routes/worksRoutes.js';
import { riskRouter } from './routes/riskRoutes.js';
import { reportRouter } from './routes/reportRoutes.js';
import { notificationRouter } from './routes/notificationRoutes.js';

export const app = express();
app.use(cors({ origin: env.clientUrl }));
app.use(express.json({ limit: '10kb' }));
app.get('/api/health', (req, res) => res.json({ status: 'ok' }));
app.use('/api/auth', authRouter);
app.use('/api/dashboard', dashboardRouter);
app.use('/api/works', worksRouter);
app.use('/api/risk', riskRouter);
app.use('/api/reports', reportRouter);
app.use('/api/notifications', notificationRouter);
app.use(notFound);
app.use(errorHandler);
